### ISSUE TITLE
Mac, zsh: Screen flickers, but no input is detected

### ISSUE THREAD

**Issue by ideogram** [cornradio/dumb_menu#2]
Thanks for the noble initiative!

I need to develop for both Mac and Windows, so I tried this package.

On my Mac (M1), under ZSH, the entire menu is neatly shown but the screen and the title of the windows flickers. Moving the cursor key has no effect, pressing 'Enter' or the 'hot key' has no effect. Only escape out of the menu is CONTROL-Z.

**Comment by cornradio** [comment]
I never tried using it on the default terminal , it is flickering , I have no idea why this happen !

**Comment by cornradio** [comment]
and I haven't visit GitHub like ---- a week , I will try to figure out and fix it

**Comment by cornradio** [comment]
it is fix now.
see :  https://pypi.org/project/dumb-menu/

I add a hint to install `getch` 
```
ERROR:  can't get input 
Fix:    pip install getch
```
