### ISSUE TITLE
Screen flickers when redrawing menu

### ISSUE THREAD

**Issue by BWindey** [cornradio/dumb_menu#4]
Hi, I was looking for a good menu that would work on all platforms, and I found this really helpful.
I decided to copy your code and tweak it a bit to more suit my needs and style, but there was one major issue I had.
On Linux, when trying the demo, the menu flickers each time I use the arrow-keys to navigate. 
I looked into this, and I found a solution that works for me: ANSI escape codes. Apparently there is one that clears the screen. 
The disadvantage is that older Windows versions don't support ANSI escape codes in their terminal, so I still need detection for Windows, that will still use `os.system("cls")`.

This is the piece of code I wrote to prevent any flickering, by building up the string first, with the escape codes in front if on Unix, and then print that:
```python
def show_clean_menu(options, selected_index):
    if os.name == 'nt':
        os.system("cls")
        result = ""
    else:
        result = "\033[2J\033[H"

    result += '\n'.join(
        f"{'>' * (selected_index == i)} {option}"
        for i, option in enumerate(options)
    )
    print(result)
```
I used a generator-expression to build up the result-string, but that can of course be turned back into a simple for-loop if you prefer that style.

This was a small annoyance I had, and wanted to share if you find this useful.

**Comment by cornradio** [comment]
can you send me a video or gif to show that? 

---- i don't really get it.

MENU FLICKER is because every time ,you move , it will re-print the menu with right cursor position , and , idont know how to avoid that 

---- isuggest using short cut key instead of moving the cursor !

**Comment by BWindey** [comment]
Indeed, that's why the flicker happens when moving the cursor, but this ASCII code clears the terminal as well:
```py
"\033[2J\033[H"
```
Printing that in front of the string containing the menu will result in no flicker (at leas on my machine).

**Comment by cornradio** [comment]
> Indeed, that's why the flicker happens when moving the cursor, but this ASCII code clears the terminal as well:
> 
> ```python
> "\033[2J\033[H"
> ```
> 
> Printing that in front of the string containing the menu will result in no flicker (at leas on my machine).

OK LET ME TRY IT ON MY MACHINE' AND IF YOU WANT TO HAVE A PULL REQUEST?

**Comment by cornradio** [comment]
` print("\033[2J\033[H") ` and i m really not sure if this will work on all linux and mac platform , this project must put "uesable" at first

and i tested it on my  wsl , using  "\033[2J\033[H"  still feels flickering

**Comment by BWindey** [comment]
Hmm, ok.
I'll close this then, as my suggestion doesn't seem to work everywhere.
